# Generated by Django 5.0.3 on 2024-05-04 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(default=0, max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('quantity', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=13)),
                ('education', models.CharField(max_length=255, null=True)),
                ('religion', models.CharField(blank=True, max_length=100)),
                ('next_of_kin', models.CharField(default=None, max_length=200)),
                ('sitter_number', models.CharField(default=None, max_length=10, unique=True)),
                ('NIN', models.CharField(max_length=14, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Baby',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(default=0)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('baby_Number', models.IntegerField()),
                ('baby_Bringer', models.CharField(max_length=100)),
                ('parent_Name', models.CharField(max_length=100)),
                ('period_of_stay', models.ForeignKey(default=0, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.period')),
            ],
        ),
    ]
