# Generated by Django 5.0.3 on 2024-05-09 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baby',
            name='period_of_stay',
            field=models.CharField(blank=True, default='Full Day', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='baby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.baby'),
        ),
        migrations.AlterField(
            model_name='baby',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baby',
            name='time_in',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='period',
            name='period',
            field=models.CharField(default='Full Day', max_length=100),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, null=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, null=True)),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.baby')),
                ('period_of_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.period')),
            ],
        ),
    ]
