# Generated by Django 5.0.3 on 2024-05-07 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='age',
            field=models.PositiveIntegerField(blank=True, default=1),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
