# Generated by Django 5.0.3 on 2024-05-08 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='date_of_registration',
            field=models.DateField(default=datetime.date(2024, 5, 8), null=True),
        ),
    ]
