# Generated by Django 5.0.3 on 2024-05-14 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0002_additem_babypayment_itemselling_sitter_on_duty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='NIN',
            field=models.CharField(max_length=14, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='contact',
            field=models.CharField(max_length=13, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.RegexValidator(message='Enter a valid Country contact', regex='^(\\+256|0)\\d{9}$')]),
        ),
    ]
