# Generated by Django 5.0.3 on 2024-05-08 18:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0002_sitter_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='date_of_registration',
            field=models.DateField(default=django.utils.timezone.now, null=True),
        ),
    ]
