# Generated by Django 5.0.3 on 2024-05-08 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0002_alter_sitter_age_alter_sitter_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='age',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
