# Generated by Django 5.0.3 on 2024-04-26 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0002_sitter_education_sitter_next_of_kin_sitter_religion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='babyBringer',
            new_name='baby_Bringer',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='babyNum',
            new_name='baby_Number',
        ),
        migrations.RenameField(
            model_name='baby',
            old_name='parentName',
            new_name='parent_Name',
        ),
    ]
