# Generated by Django 5.0.3 on 2024-05-08 21:10

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0003_alter_sitter_date_of_registration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter',
            name='date_of_registration',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
    ]
