# Generated by Django 5.0.3 on 2024-05-09 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0003_alter_baby_status_sitter_on_duty_baby_assigned_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='time_out',
            field=models.TimeField(),
        ),
    ]
