# Generated by Django 5.0.3 on 2024-05-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0004_alter_baby_time_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='time_out',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
