# Generated by Django 5.0.3 on 2024-05-08 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0004_alter_sitter_date_of_registration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='date_of_registration',
        ),
    ]
