# Generated by Django 5.0.3 on 2024-04-26 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0004_baby_time_of_arrival'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baby',
            name='time_of_arrival',
        ),
        migrations.AddField(
            model_name='sitter',
            name='NIN',
            field=models.IntegerField(max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='age',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='sitter_number',
            field=models.CharField(default=None, max_length=10, unique=True),
        ),
    ]
