# Generated by Django 5.0.3 on 2024-05-15 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0004_alter_itemselling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='baby_Number',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='amount',
            field=models.IntegerField(blank=True, choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '450000')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='amount_paid',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1000)]),
        ),
    ]
