# Generated by Django 5.0.3 on 2024-05-15 12:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0005_alter_baby_baby_number_alter_babypayment_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='age',
            field=models.PositiveIntegerField(default=0, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)]),
        ),
    ]
