# Generated by Django 5.0.3 on 2024-05-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0005_alter_baby_time_out'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sale',
            new_name='Item',
        ),
    ]
