# Generated by Django 5.0.3 on 2024-04-27 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0006_alter_sitter_nin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='baby',
            name='period_of_stay',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.period'),
        ),
    ]
