# Generated by Django 5.0.3 on 2024-05-11 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0007_additem_rename_item_itemselling'),
    ]

    operations = [
        migrations.RenameField(
            model_name='additem',
            old_name='item',
            new_name='doll_name',
        ),
        migrations.RemoveField(
            model_name='itemselling',
            name='item',
        ),
        migrations.RemoveField(
            model_name='itemselling',
            name='price',
        ),
        migrations.AddField(
            model_name='itemselling',
            name='amount_paid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='itemselling',
            name='doll_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='quantity',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='status',
            field=models.CharField(choices=[('On Duty', 'On Duty')], max_length=100),
        ),
    ]
