# Generated by Django 5.0.3 on 2024-05-15 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0007_stock_alter_baby_age_alter_sitter_nin_issue_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_stock',
            name='date_of_issue',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
