# Generated by Django 5.0.3 on 2024-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0008_alter_baby_period_of_stay_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True)),
                ('unit_price', models.IntegerField(blank=True, max_length=255, null=True)),
                ('quantity_sold', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
