# Generated by Django 5.0.3 on 2024-05-11 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0008_rename_item_additem_doll_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemselling',
            name='price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
