# Generated by Django 5.0.3 on 2024-05-15 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0008_alter_issue_stock_date_of_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
