# Generated by Django 5.0.3 on 2024-05-15 18:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0009_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_stock',
            name='date_of_issue',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
