# Generated by Django 5.0.3 on 2024-04-29 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0009_sales_delete_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=255, null=True)),
                ('unit_price', models.IntegerField(null=True)),
                ('quantity_sold', models.IntegerField(default=0, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Sales',
        ),
    ]
