# Generated by Django 5.0.3 on 2024-05-12 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0010_alter_itemselling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baby',
            name='period_of_stay',
            field=models.CharField(blank=True, choices=[('Full Day', 'Full Day'), ('Half Day', 'Half Day')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='status',
            field=models.BooleanField(choices=[('On Duty', 'On Duty')], max_length=100),
        ),
    ]
