# Generated by Django 5.0.3 on 2024-05-16 18:19

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0010_alter_issue_stock_date_of_issue_alter_stock_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_stock',
            name='date_of_issue',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issue_stock',
            name='stock_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.stock'),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='amount_paid',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='baby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.baby'),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='doll_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='NIN',
            field=models.CharField(max_length=14, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)]),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
