# Generated by Django 5.0.3 on 2024-04-29 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0011_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
