# Generated by Django 5.0.3 on 2024-05-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0011_alter_issue_stock_date_of_issue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselling',
            name='price',
            field=models.IntegerField(default=5000),
        ),
    ]
