# Generated by Django 5.0.3 on 2024-05-12 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0011_alter_baby_period_of_stay_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='status',
            field=models.BooleanField(choices=[('On Duty', True), ('Off Duty', False)], default=False),
        ),
    ]
