# Generated by Django 5.0.3 on 2024-05-12 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0012_alter_sitter_on_duty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='status',
            field=models.BooleanField(choices=[('On Duty', True), ('Off Duty', False)]),
        ),
    ]
