# Generated by Django 5.0.3 on 2024-05-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0012_alter_itemselling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselling',
            name='amount_paid',
            field=models.IntegerField(),
        ),
    ]
