# Generated by Django 5.0.3 on 2024-05-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0013_alter_itemselling_amount_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additem',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
