# Generated by Django 5.0.3 on 2024-05-01 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0013_remove_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='quantity_sold',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_price',
            field=models.IntegerField(),
        ),
    ]
