# Generated by Django 5.0.3 on 2024-05-12 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0013_alter_sitter_on_duty_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitter_on_duty',
            name='status',
            field=models.BooleanField(blank=True, choices=[(True, 'On Duty'), (False, 'Off Duty')], null=True),
        ),
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(blank=True, choices=[(10000, '10000'), (15000, '15000'), (300000, '300000'), (450000, '45000')], default=0, null=True)),
                ('date_of_payment', models.DateTimeField(auto_now_add=True, null=True)),
                ('duration_of_pay', models.CharField(choices=[('Half day', 'Half day'), ('Full Day', 'Full Day'), ('Monthly Full Day', 'Monthly Full Day'), ('Monthly Half Day', 'Monthly Half Day')], max_length=100)),
                ('amount_paid', models.IntegerField(default=0)),
                ('baby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.baby')),
                ('period_of_stay', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.period')),
            ],
        ),
        migrations.CreateModel(
            name='SitterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_baby', models.IntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=3000)),
                ('sitter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.sitter_on_duty')),
            ],
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
