# Generated by Django 5.0.3 on 2024-05-01 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0014_alter_sale_quantity_sold_alter_sale_unit_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='amount',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
