# Generated by Django 5.0.3 on 2024-05-18 15:09

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0015_alter_itemselling_amount_paid_alter_itemselling_baby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue_stock',
            name='date_of_issue',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='issue_stock',
            name='quantity',
            field=models.PositiveIntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='baby',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dayStarApp.baby'),
        ),
    ]
