# Generated by Django 5.0.3 on 2024-05-18 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0018_alter_itemselling_amount_paid_alter_itemselling_baby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselling',
            name='price',
            field=models.IntegerField(),
        ),
    ]
