# Generated by Django 5.0.3 on 2024-05-18 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0019_alter_itemselling_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemselling',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
