# Generated by Django 5.0.3 on 2024-05-18 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0020_alter_itemselling_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_stock',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='issue_stock',
            name='date_of_issue',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='itemselling',
            name='amount_paid',
            field=models.IntegerField(blank=True),
        ),
    ]
