# Generated by Django 5.0.3 on 2024-05-19 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0021_issue_stock_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='baby',
            old_name='assigned_to',
            new_name='assigned_To',
        ),
    ]
