# Generated by Django 5.0.3 on 2024-05-19 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0022_rename_assigned_to_baby_assigned_to'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sitterpayment',
            old_name='amount_paid',
            new_name='amount_per_baby',
        ),
    ]
