# Generated by Django 5.0.3 on 2024-05-19 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0023_rename_amount_paid_sitterpayment_amount_per_baby'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babypayment',
            old_name='amount',
            new_name='total_Fee',
        ),
    ]
