# Generated by Django 5.0.3 on 2024-05-20 17:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0025_alter_baby_assigned_to_alter_baby_period_of_stay_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitter',
            name='date_of_birth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
