# Generated by Django 5.0.3 on 2024-05-20 20:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dayStarApp', '0027_alter_sitter_on_duty_sitter_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue_stock',
            name='issued_To',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='baby',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter both names with no special characters', regex="^(?=.{1,100}$)[A-Za-z]+(?:[\\'\\s-][A-Za-z]+)* [A-Za-z]+(?:[\\'\\s-][A-Za-z]+)*$")]),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='name',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Enter both names with no special characters', regex="^(?=.{1,100}$)[A-Za-z]+(?:[\\'\\s-][A-Za-z]+)* [A-Za-z]+(?:[\\'\\s-][A-Za-z]+)*$")]),
        ),
    ]
